// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";

  /*
  J+ PKG
  Programmed by Go Shoemake <3
  -----------------------------
  Implemented through Literate CoffeeScript.
  Source code and resources are available at https://github.com/literallybenjam/jplus/.
  Written for the CoffeeScript 1.10.0 compiler.
   */

  /*
  MIT License
  
  Copyright (c) 2016 Go Shoemake
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
   */
  var data, init, initScript, pkgs, receiveMessage, settings, targetorigin, title, tools;

  pkgs = {};

  init = function(using) {
    ℹ.initScript(using);
    if (typeof parent !== "undefined" && parent !== null) {
      parent.postMessage(window["📦"], ℹ.targetorigin);
    }
  };

  receiveMessage = function(e) {
    if (e.origin !== parent.location.origin) {
      return;
    }
    init(e.data);
    window.removeEventListener("message", receiveMessage, false);
  };

  window.addEventListener("message", receiveMessage, false);

  data = Object.defineProperty({}, "📛", {
    get: function() {
      return ℹ.title;
    }
  });

  Object.defineProperties(window, {
    "📦": {
      value: data
    },
    "data": {
      value: data,
      writable: true,
      configurable: true
    },
    "j-plus-data": {
      value: data,
      writable: true,
      configurable: true
    },
    "jplus_data": {
      value: data,
      writable: true,
      configurable: true
    }
  });

  initScript = function() {};

  targetorigin = "*";

  title = document.title;

  settings = Object.defineProperties({}, {
    initScript: {
      get: function() {
        return initScript;
      },
      set: function(n) {
        if (n instanceof Function) {
          return initScript = n;
        } else {
          return initScript = Function(n);
        }
      }
    },
    targetorigin: {
      get: function() {
        return targetorigin;
      },
      set: function(n) {
        return targetorigin = String(n);
      }
    },
    title: {
      get: function() {
        return title;
      },
      set: function(n) {
        return title = String(n);
      }
    }
  });

  Object.freeze(settings);

  Object.defineProperties(window, {
    "ℹ": {
      value: settings
    },
    "settings": {
      value: settings,
      writable: true,
      configurable: true
    },
    "j-plus-settings": {
      value: settings,
      writable: true,
      configurable: true
    },
    "jplus_settings": {
      value: settings,
      writable: true,
      configurable: true
    }
  });

  tools = {
    handleEvent: function(e) {
      var from;
      switch (e.type) {
        case "message":
          if (pkgs.hasOwnProperty(e.source.location.href)) {
            from = e.source.location.href;
            Object.freeze(e.data);
            if (pkgs[from].into != null) {
              Object.defineProperty(window["📦"], pkgs[from].into, {
                value: e.data,
                enumerable: true,
                configurable: true
              });
            }
            if (pkgs[from].andthen != null) {
              pkgs[from].andthen(e.data);
            }
            document.body.removeChild(pkgs[from].frame);
            delete pkgs[from];
          }
      }
    },
    loadPackage: function(from, using, into, andthen) {
      var a, from_origin, pkgelt;
      a = document.createElement('A');
      a.href = from;
      from = a.href;
      from_origin = a.origin;
      if (from_origin == null) {
        from_origin = a.protocol + "//" + a.host;
      }
      pkgelt = document.createElement('IFRAME');
      pkgelt.style.display = "none";
      if (pkgs[from] != null) {
        throw new TypeError("package '" + from + "' has already been queued");
      }
      Object.defineProperty(pkgs, from, {
        value: Object.freeze({
          frame: pkgelt,
          into: into,
          andthen: andthen
        }),
        enumerable: true,
        configurable: true
      });
      pkgelt.addEventListener("load", (function() {
        return pkgelt.contentWindow.postMessage(using, from_origin);
      }), false);
      pkgelt.src = from;
      if (document.body != null) {
        document.body.appendChild(pkgelt);
      } else {
        document.addEventListener("DOMContentLoaded", (function() {
          return document.body.appendChild(pkgelt);
        }), false);
      }
    }
  };

  Object.freeze(tools);

  Object.defineProperties(window, {
    "🛠": {
      value: tools
    },
    "tools": {
      value: tools,
      writable: true,
      configurable: true
    },
    "j-plus-tools": {
      value: tools,
      writable: true,
      configurable: true
    },
    "jplus_tools": {
      value: tools,
      writable: true,
      configurable: true
    }
  });

}).call(this);
